# Generated by Django 2.2.6 on 2019-11-03 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='companies.Company')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Anticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Valor antecipado')),
                ('status', models.CharField(choices=[('WAITING', 'Aguardando confirmação'), ('CONFIRMED', 'Antecipado'), ('DENIED', 'Negado')], default='WAITING', max_length=20, verbose_name='Situação')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.Payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'antecipação',
                'verbose_name_plural': 'antecipações',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='AnticipationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Aguardando confirmação'), ('CONFIRMED', 'Antecipado'), ('DENIED', 'Negado')], max_length=1, verbose_name='Situação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('anticipation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.Anticipation', verbose_name='Antecipação')),
            ],
            options={
                'verbose_name': 'histórico de antecipação',
                'verbose_name_plural': 'históricos de antecipações',
                'ordering': ['-created'],
                'unique_together': {('anticipation', 'status')},
            },
        ),
    ]
