# Generated by Django 2.2.6 on 2019-11-04 03:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='payment',
            field=models.OneToOneField(limit_choices_to=models.Q(('due_date__gt', datetime.date(2019, 11, 4)), ('anticipation__isnull', True)), on_delete=django.db.models.deletion.CASCADE, to='payments.Payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='anticipation',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Aguardando confirmação'), ('CONFIRMED', 'Antecipado'), ('DENIED', 'Negado')], default='WAITING', editable=False, max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='anticipationhistory',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Aguardando confirmação'), ('CONFIRMED', 'Antecipado'), ('DENIED', 'Negado')], max_length=20, verbose_name='Situação'),
        ),
    ]
