# Generated by Django 2.2.6 on 2019-11-05 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191104_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='payment',
            field=models.OneToOneField(limit_choices_to=models.Q(('due_date__gt', datetime.date(2019, 11, 5)), ('anticipation__isnull', True)), on_delete=django.db.models.deletion.CASCADE, to='payments.Payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='companies.Company', verbose_name='Empresa'),
        ),
    ]
